# All delays are in seconds
googleTranslateDelay : 5
listingLoadDelay : 2



# review Extraction.
retrieveHostResponse : 0 #Set to 1 if you want the host's response, else set to 0.
maxReviewsPerListing : 50 #Control how many reviews are extracted from a single listing

# search
destination : "New York"
destinationUniquifier : "NY" # This allows you specify the specific destination if multiple places have the same name.
houseListingSuffix : "Stays" # This tells the search API to return only house listings and not experiences
numListingsFromSearch : 300 # Maximum number of listings to get from a single location

# output
listingsFile: "listings.json"
populatedListingsFile: "populatedListings.json"