readMoreSelector: "._b0ybw8s"
nextPageSelector: "#reviews ._r4n1gzb"
translateReviewsSelector: "#reviews ._bv5p5f"
reviewTextSelector: "#reviews ._czm8crp"
listingDetailsSelector: "._n5lh69r"
amenitiesSelector: "#amenities ._1p3joamp"
amenitiesPopUpSelector: "._7lvai1"
