readMoreSelector: "._b0ybw8s"
nextPageSelector: "#reviews ._r4n1gzb"
translateReviewsSelector: "#reviews ._bv5p5f"
reviewTag: "#reviews"
textSelector: "._czm8crp"
amenitySectionNameSelector: "._1p0spma2"
unavailableAmenitySelector: "._krjbj"
listingDetailsSelector: "._n5lh69r"
amenitiesSelector: "#amenities ._1p3joamp"
amenitiesPopUpSelector: "._7lvai1"
