readMoreSelector: "._b0ybw8s"
nextPageSelector: "._r4n1gzb"
translateReviewsSelector: "#reviews ._bv5p5f"
reviewTag: "#reviews"
textSelector: "._czm8crp"
amenitySectionNameSelector: "._1p0spma2"
unavailableAmenitySelector: "._krjbj"
listingDetailsSelector: "._n5lh69r"
amenitiesSelector: "#amenities ._1p3joamp"
amenitiesPopUpSelector: "._7lvai1"
searchEntrySelector: "._1n8ekdm"
locationSearchSelector: "._1f8ev6q"
searchListingSelector: "._8ssblpx"
searchListingURLSelector: "._15tommw"
listingRatingSelector: "._tghtxy2"
listingReviewCountSelector: "._1plk0jz1"
listingPriceSelector: "._krjbj"
